version: '2'

services:
  app:
    image: 'contrato'
    build: .
    ports:
      - 8080:8080

    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contratos
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=contratos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin