# This is a basic workflow to help you get started with Actions

name: Build e Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurando o java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
                
      - name: config bd
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: 'contrato' 
          postgresql user: 'postgres'
          postgresql password: 'admin'   
          
      - name: Look for gradlew
        run: find / -type f -name "gradlew"
      
      - name: Permissão para executar o gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
     
        
      - name: Deploy no Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "demo-dsc" #Must be unique in Heroku
          heroku_email: "william.costa@escolar.ifrn.edu.br"
          usedocker: "true"
      
