
name: Build e Deploy

on:
  push:
    branches:
      -main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Banco de dados
        uses: huaxk/postgis-action@v1
        with:
         postgresql version: '11'
         postgresql password: ${{ secrets.DatabasePassword }}
         postgresql user: 'postgres'
         postgresql db: 'contrato'
      - name: Configurando o java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adop'        
      - name: Validate Gradlew wrapper 
        uses: gradlew/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradlew
        run: ./gradlew build
        
       
      
      
        
      
      
        
        
      

