name: Build e Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configurando o java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: config bd
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'  # See https://hub.docker.com/_/postgres for available versions
          postgresql db: 'contrato' 
          postgresql user: 'postgres'
          postgresql password: '12345'
      - name: Permissão para executar o gradlew
        run: chmod +x ./runner/work/contratos/contratos/contrato/gradlew
      - name: Build with Gradle
        run: ./gradlew build
     
